name: task3
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  shimmer: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

dev_dependencies:
  build_runner: ^1.11.5
  effective_dart: ^1.3.0
  pedantic: ^1.9.2
  lint: ^1.3.0





  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:

    - assets/images/1643376671baby-color-silhouette-low-poly.svg

#  fonts:
#    - family: IrishGrover
#      fonts:
#        - asset: assets/fonts/IrishGrover-Regular.ttf


